osqp-eigen: OsqpEigen::Settings Class Reference
OsqpEigen::Settings Class Reference
settings class is a wrapper of the OSQP OSQPSettings struct.
#include <OsqpEigen/Settings.hpp>
Public Member Functions
Settings ()
Constructor.
~Settings ()
Deconstructor.
void resetDefaultSettings ()
Reset the default settings for the optimization problem.
void setRho (const double rho)
Set the ADMM step rho.
void setSigma (const double sigma)
Set the ADMM step sigma.
void setScaling (const int scaling)
Set the heuristic data scaling iterations.
void setAdaptiveRho (const bool isRhoStepSizeAdactive)
Set if the rho step size adaptive feature is active.
void setAdaptiveRhoInterval (const int rhoInterval)
Set the number of iterations between rho adaptations rho.
void setAdaptiveRhoTolerance (const double adaptiveRhoTolerance)
Set the tolerance for adapting rho.
void setAdaptiveRhoFraction (const double adaptiveRhoFraction)
Set the interval for adapting rho (fraction of the setup time).
void setMaxIteraction (const int maxIteration)
Set the max number of iterations.
void setMaxIteration (const int maxIteration)
Set the max number of iterations.
void setAbsoluteTolerance (const double absoluteTolerance)
Set the absolute convergence tolerance.
void setRelativeTolerance (const double relativeTolerance)
Set the relative convergence tolerance.
void setPrimalInfeasibilityTollerance (const double primalInfeasibilityTollerance)
Set the primal infeasibility tolerance.
void setDualInfeasibilityTollerance (const double dualInfeasibilityTollerance)
Set the dual infeasibility tolerance.
void setAlpha (const double alpha)
Set the relaxation parameter.
void setLinearSystemSolver (const int linsysSolver)
Set linear solver.
void setDelta (const double delta)
Set the relaxation parameter for polish.
void setPolish (const bool polish)
Set if the polish feature is active.
void setPolishRefineIter (const int polishRefineIter)
Set the iterative refinement steps in polish.
void setVerbosity (const bool isVerbose)
Set the Verbose mode.
void setScaledTerimination (const bool scaledTermination)
Set the scaled termination criteria.
void setCheckTermination (const int checkTermination)
Set check termination interval.
void setWarmStart (const bool warmStart)
Set warm start.
void setTimeLimit (const double timeLimit)
Set the maximum number of seconds allowed to solve the problem.
OSQPSettings *const & getSettings () const
Get a pointer to Settings struct.
Detailed Description
settings class is a wrapper of the OSQP OSQPSettings struct.
All the setter methods refer to this particular kind of optimizer. Here you can find further information.
Definition at line 25 of file Settings.hpp.
Constructor & Destructor Documentation
Settings()
OsqpEigen::Settings::Settings ()
Constructor.
Definition at line 14 of file Settings.cpp.
~Settings()
OsqpEigen::Settings::~Settings ()
Deconstructor.
Definition at line 20 of file Settings.cpp.
Member Function Documentation
getSettings()
OSQPSettings *const & OsqpEigen::Settings::getSettings () const
Get a pointer to Settings struct.
Returns
a const pointer to OSQPSettings struct.
Definition at line 195 of file Settings.cpp.
resetDefaultSettings()
void OsqpEigen::Settings::resetDefaultSettings ()
Reset the default settings for the optimization problem.
Definition at line 25 of file Settings.cpp.
setAbsoluteTolerance()
void OsqpEigen::Settings::setAbsoluteTolerance (const double absoluteTolerance)
Set the absolute convergence tolerance.
Parameters
absoluteTolerance absoulte tolerance of the solver.
Definition at line 100 of file Settings.cpp.
setAdaptiveRho()
void OsqpEigen::Settings::setAdaptiveRho (const bool isRhoStepSizeAdactive)
Set if the rho step size adaptive feature is active.
Parameters
isRhoStepSizeAdactive if True the feature is active.
Definition at line 45 of file Settings.cpp.
References std::endl().
setAdaptiveRhoFraction()
void OsqpEigen::Settings::setAdaptiveRhoFraction (const double adaptiveRhoFraction)
Set the interval for adapting rho (fraction of the setup time).
Parameters
adaptiveRhoFraction interval of the adapting rho.
Definition at line 75 of file Settings.cpp.
References std::endl().
setAdaptiveRhoInterval()
void OsqpEigen::Settings::setAdaptiveRhoInterval (const int rhoInterval)
Set the number of iterations between rho adaptations rho.
If 0, it is automatic.
Parameters
rhoInterval number of iterations.
Definition at line 55 of file Settings.cpp.
References std::endl().
setAdaptiveRhoTolerance()
void OsqpEigen::Settings::setAdaptiveRhoTolerance (const double adaptiveRhoTolerance)
Set the tolerance for adapting rho.
The new rho has to be X times larger or 1/X times smaller than the current one to trigger a new factorization.
Parameters
adaptiveRhoTolerance is the tolerance.
Definition at line 65 of file Settings.cpp.
References std::endl().
setAlpha()
void OsqpEigen::Settings::setAlpha (const double alpha)
Set the relaxation parameter.
Parameters
alpha is the relaxation parameter.
Definition at line 120 of file Settings.cpp.
setCheckTermination()
void OsqpEigen::Settings::setCheckTermination (const int checkTermination)
Set check termination interval.
If 0, termination checking is disabled.
Parameters
checkTermination if 0 the termination checking is disabled.
Definition at line 175 of file Settings.cpp.
setDelta()
void OsqpEigen::Settings::setDelta (const double delta)
Set the relaxation parameter for polish.
Parameters
delta is the relaxation parameter.
Definition at line 130 of file Settings.cpp.
References std::endl().
setDualInfeasibilityTollerance()
void OsqpEigen::Settings::setDualInfeasibilityTollerance (const double dualInfeasibilityTollerance)
Set the dual infeasibility tolerance.
Parameters
dualInfeasibilityTollerance tolerace of the dual variables.
Definition at line 115 of file Settings.cpp.
setLinearSystemSolver()
void OsqpEigen::Settings::setLinearSystemSolver (const int linsysSolver)
Set linear solver.
Parameters
linsysSolver is the name of the solver
Definition at line 125 of file Settings.cpp.
setMaxIteraction()
void OsqpEigen::Settings::setMaxIteraction (const int maxIteration)
Set the max number of iterations.
Parameters
maxIteration max number of iteration
Definition at line 90 of file Settings.cpp.
setMaxIteration()
void OsqpEigen::Settings::setMaxIteration (const int maxIteration)
Set the max number of iterations.
Parameters
maxIteration max number of iteration
Definition at line 95 of file Settings.cpp.
setPolish()
void OsqpEigen::Settings::setPolish (const bool polish)
Set if the polish feature is active.
Parameters
polish if True the feature is active.
Definition at line 140 of file Settings.cpp.
References std::endl().
setPolishRefineIter()
void OsqpEigen::Settings::setPolishRefineIter (const int polishRefineIter)
Set the iterative refinement steps in polish.
Parameters
polishRefineIter iterative refinement step.
Definition at line 150 of file Settings.cpp.
References std::endl().
setPrimalInfeasibilityTollerance()
void OsqpEigen::Settings::setPrimalInfeasibilityTollerance (const double primalInfeasibilityTollerance)
Set the primal infeasibility tolerance.
Parameters
primalInfeasibilityTollerance tolerace of the primal variables.
Definition at line 110 of file Settings.cpp.
setRelativeTolerance()
void OsqpEigen::Settings::setRelativeTolerance (const double relativeTolerance)
Set the relative convergence tolerance.
Parameters
relativeTolerance relative tolerance of the solver.
Definition at line 105 of file Settings.cpp.
setRho()
void OsqpEigen::Settings::setRho (const double rho)
Set the ADMM step rho.
Parameters
rho a ADMM step constant.
Definition at line 30 of file Settings.cpp.
setScaledTerimination()
void OsqpEigen::Settings::setScaledTerimination (const bool scaledTermination)
Set the scaled termination criteria.
Parameters
scaledTermination if true the scaled termination criteria is used.
Definition at line 170 of file Settings.cpp.
setScaling()
void OsqpEigen::Settings::setScaling (const int scaling)
Set the heuristic data scaling iterations.
If 0, scaling disabled.
Parameters
scaling is the heuristic data scaling iteration.
Definition at line 40 of file Settings.cpp.
setSigma()
void OsqpEigen::Settings::setSigma (const double sigma)
Set the ADMM step sigma.
Parameters
sigma a ADMM step constant.
Definition at line 35 of file Settings.cpp.
setTimeLimit()
void OsqpEigen::Settings::setTimeLimit (const double timeLimit)
Set the maximum number of seconds allowed to solve the problem.
Parameters
timeLimit is the time limit in seconds. If 0, then disabled.
Definition at line 185 of file Settings.cpp.
References std::endl().
setVerbosity()
void OsqpEigen::Settings::setVerbosity (const bool isVerbose)
Set the Verbose mode.
Parameters
isVerbose if true the verbose mode is activate.
Definition at line 160 of file Settings.cpp.
References std::endl().
setWarmStart()
void OsqpEigen::Settings::setWarmStart (const bool warmStart)
Set warm start.
Parameters
warmStart if true the warm start is set.
Definition at line 180 of file Settings.cpp.
The documentation for this class was generated from the following files:
Settings.hpp
Settings.cpp