osqp-eigen: OsqpEigen::Data Class Reference
OsqpEigen::Data Class Reference
Data class is a wrapper of the OSQP OSQPData struct.
#include <OsqpEigen/Data.hpp>
Public Member Functions
Data ()
Constructor.
Data (int n, int m)
Constructor.
~Data ()
Deconstructor.
void clearHessianMatrix ()
Clear the hessian matrix.
void clearLinearConstraintsMatrix ()
Clear the linear constraints matrix.
void setNumberOfVariables (int n)
Set the number of variables.
void setNumberOfConstraints (int m)
Set the number of constraints.
template<typename Derived >
bool setHessianMatrix (const Eigen::SparseCompressedBase< Derived > &hessianMatrix)
Set the quadratic part of the cost function (Hessian).
bool setGradient (Eigen::Ref< Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> gradientVector)
Set the linear part of the cost function (Gradient).
template<typename Derived >
bool setLinearConstraintsMatrix (const Eigen::SparseCompressedBase< Derived > &linearConstraintsMatrix)
Set the linear constraint matrix A (size m x n)
bool setLowerBound (Eigen::Ref< Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> lowerBoundVector)
Set the array for lower bound (size m).
bool setUpperBound (Eigen::Ref< Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> upperBoundVector)
Set the array for upper bound (size m).
bool setBounds (Eigen::Ref< Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> lowerBound, Eigen::Ref< Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> upperBound)
Set the array for upper and lower bounds (size m).
OSQPData *const & getData () const
Get the OSQPData struct.
bool isSet () const
Verify if all the matrix and vectors are already set.
Detailed Description
Data class is a wrapper of the OSQP OSQPData struct.
Definition at line 28 of file Data.hpp.
Constructor & Destructor Documentation
Data() [1/2]
OsqpEigen::Data::Data ()
Constructor.
Definition at line 15 of file Data.cpp.
Data() [2/2]
OsqpEigen::Data::Data (int n, int m)
Constructor.
Parameters
n is the number of variables;
m is the number of constraints.
Definition at line 29 of file Data.cpp.
References setNumberOfConstraints(), and setNumberOfVariables().
~Data()
OsqpEigen::Data::~Data ()
Deconstructor.
Definition at line 64 of file Data.cpp.
Member Function Documentation
clearHessianMatrix()
void OsqpEigen::Data::clearHessianMatrix ()
Clear the hessian matrix.
Definition at line 46 of file Data.cpp.
Referenced by OsqpEigen::Solver::updateHessianMatrix().
clearLinearConstraintsMatrix()
void OsqpEigen::Data::clearLinearConstraintsMatrix ()
Clear the linear constraints matrix.
Definition at line 55 of file Data.cpp.
getData()
OSQPData *const & OsqpEigen::Data::getData () const
Get the OSQPData struct.
Returns
a const point to the OSQPData struct.
Definition at line 83 of file Data.cpp.
isSet()
bool OsqpEigen::Data::isSet () const
Verify if all the matrix and vectors are already set.
Returns
true if all the OSQPData struct are set.
Definition at line 88 of file Data.cpp.
setBounds()
bool OsqpEigen::Data::setBounds (Eigen::Ref< Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> lowerBound, Eigen::Ref< Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> upperBound)
Set the array for upper and lower bounds (size m).
Parameters
lowerBound is the lower bound constraint.
upperBound is the upper bound constraint.
Note
the elements of the upperBound and lowerBound are not copied inside the library. The user has to guarantee that the lifetime of the object passed is the same of the OsqpEigen object.
Returns
true/false in case of success/failure.
Definition at line 138 of file Data.cpp.
setGradient()
bool OsqpEigen::Data::setGradient (Eigen::Ref< Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> gradientVector)
Set the linear part of the cost function (Gradient).
Parameters
gradientVector is the Gradient vector.
Note
the elements of the gradient are not copied inside the library. The user has to guarantee that the lifetime of the object passed is the same of the OsqpEigen object
Returns
true/false in case of success/failure.
Definition at line 102 of file Data.cpp.
References std::endl().
setHessianMatrix()
template<typename Derived > bool OsqpEigen::Data::setHessianMatrix (const Eigen::SparseCompressedBase< Derived > & hessianMatrix)
Set the quadratic part of the cost function (Hessian).
It is assumed to be a simmetric matrix.
Parameters
hessianMatrix is the Hessian matrix.
Returns
true/false in case of success/failure.
Definition at line 13 of file Data.tpp.
References OsqpEigen::SparseMatrixHelper::createOsqpSparseMatrix(), and std::endl().
Referenced by OsqpEigen::Solver::updateHessianMatrix().
setLinearConstraintsMatrix()
template<typename Derived > bool OsqpEigen::Data::setLinearConstraintsMatrix (const Eigen::SparseCompressedBase< Derived > & linearConstraintsMatrix)
Set the linear constraint matrix A (size m x n)
Parameters
linearConstraintsMatrix is the linear constraints matrix A.
Returns
true/false in case of success/failure.
Definition at line 49 of file Data.tpp.
References OsqpEigen::SparseMatrixHelper::createOsqpSparseMatrix(), and std::endl().
setLowerBound()
bool OsqpEigen::Data::setLowerBound (Eigen::Ref< Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> lowerBoundVector)
Set the array for lower bound (size m).
Parameters
lowerBoundVector is the lower bound constraint.
Note
the elements of the lowerBoundVector are not copied inside the library. The user has to guarantee that the lifetime of the object passed is the same of the OsqpEigen object
Returns
true/false in case of success/failure.
Definition at line 114 of file Data.cpp.
References std::endl().
setNumberOfConstraints()
void OsqpEigen::Data::setNumberOfConstraints (int m)
Set the number of constraints.
Parameters
m is the number of constraints.
Definition at line 77 of file Data.cpp.
Referenced by Data().
setNumberOfVariables()
void OsqpEigen::Data::setNumberOfVariables (int n)
Set the number of variables.
Parameters
n is the number of variables.
Definition at line 71 of file Data.cpp.
Referenced by Data().
setUpperBound()
bool OsqpEigen::Data::setUpperBound (Eigen::Ref< Eigen::Matrix< c_float, Eigen::Dynamic, 1 >> upperBoundVector)
Set the array for upper bound (size m).
Parameters
upperBoundVector is the upper bound constraint.
Note
the elements of the upperBoundVector are not copied inside the library. The user has to guarantee that the lifetime of the object passed is the same of the OsqpEigen object.
Returns
true/false in case of success/failure.
Definition at line 126 of file Data.cpp.
References std::endl().
The documentation for this class was generated from the following files:
Data.hpp
Data.cpp
Data.tpp