osqp-eigen: OsqpEigen::SparseMatrixHelper Namespace Reference
OsqpEigen::SparseMatrixHelper Namespace Reference
SparseMatrixHelper namespace is a namspace that contains helper function to handle osqp matrix.
Functions
template<typename Derived >
bool createOsqpSparseMatrix (const Eigen::SparseCompressedBase< Derived > &eigenSparseMatrix, csc *&osqpSparseMatrix)
Allocate an osqpSparseMatrix struct.
template<typename T >
bool osqpSparseMatrixToEigenSparseMatrix (const csc *const &osqpSparseMatrix, Eigen::SparseMatrix< T > &eigenSparseMatrix)
Convert an osqp sparse matrix into an eigen sparse matrix.
template<typename T >
bool osqpSparseMatrixToTriplets (const csc *const &osqpSparseMatrix, std::vector< Eigen::Triplet< T >> &tripletList)
Convert an osqp sparse matrix into a eigen triplet list.
template<typename Derived , typename T >
bool eigenSparseMatrixToTriplets (const Eigen::SparseCompressedBase< Derived > &eigenSparseMatrix, std::vector< Eigen::Triplet< T >> &tripletList)
Convert an eigen sparse matrix into a eigen triplet list.
Detailed Description
SparseMatrixHelper namespace is a namspace that contains helper function to handle osqp matrix.
Use it to create ot update or manage an osqp sparse matrix. osqp sparse matrix in compressed-column or triplet form.
Function Documentation
createOsqpSparseMatrix()
template<typename Derived > bool OsqpEigen::SparseMatrixHelper::createOsqpSparseMatrix (const Eigen::SparseCompressedBase< Derived > & eigenSparseMatrix, csc *& osqpSparseMatrix)
Allocate an osqpSparseMatrix struct.
NOTE: c_malloc function is used to allocate memory please call c_free to deallcate memory.
Returns
a const point to the csc struct.
Definition at line 11 of file SparseMatrixHelper.tpp.
References std::endl().
Referenced by OsqpEigen::Data::setHessianMatrix(), and OsqpEigen::Data::setLinearConstraintsMatrix().
eigenSparseMatrixToTriplets()
template<typename Derived , typename T > bool OsqpEigen::SparseMatrixHelper::eigenSparseMatrixToTriplets (const Eigen::SparseCompressedBase< Derived > & eigenSparseMatrix, std::vector< Eigen::Triplet< T >> & tripletList)
Convert an eigen sparse matrix into a eigen triplet list.
Parameters
eigenSparseMatrix is the eigen sparse matrix object;
tripletList is a std::vector containing the triplet.
Returns
a const point to the csc struct.
Definition at line 129 of file SparseMatrixHelper.tpp.
References std::endl().
Referenced by OsqpEigen::Solver::updateHessianMatrix(), and OsqpEigen::Solver::updateLinearConstraintsMatrix().
osqpSparseMatrixToEigenSparseMatrix()
template<typename T > bool OsqpEigen::SparseMatrixHelper::osqpSparseMatrixToEigenSparseMatrix (const csc *const & osqpSparseMatrix, Eigen::SparseMatrix< T > & eigenSparseMatrix)
Convert an osqp sparse matrix into an eigen sparse matrix.
Parameters
osqpSparseMatrix is a constant pointer to a constant csc struct;
eigenSparseMatrix is the eigen sparse matrix object.
Returns
a const point to the csc struct.
Definition at line 101 of file SparseMatrixHelper.tpp.
References std::vector< T >::begin(), std::vector< T >::end(), std::endl(), and osqpSparseMatrixToTriplets().
osqpSparseMatrixToTriplets()
template<typename T > bool OsqpEigen::SparseMatrixHelper::osqpSparseMatrixToTriplets (const csc *const & osqpSparseMatrix, std::vector< Eigen::Triplet< T >> & tripletList)
Convert an osqp sparse matrix into a eigen triplet list.
Parameters
osqpSparseMatrix is reference to a constant pointer to a constant csc struct;
tripletList is a std::vector containing the triplet.
Returns
a const point to the csc struct.
Definition at line 61 of file SparseMatrixHelper.tpp.
References std::endl().
Referenced by osqpSparseMatrixToEigenSparseMatrix(), OsqpEigen::Solver::updateHessianMatrix(), and OsqpEigen::Solver::updateLinearConstraintsMatrix().